<a href="https://colab.research.google.com/github/praveen310194/data_science/blob/master/Encoding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
a.dtype

dtype('int64')

In [67]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [84]:
df=pd.DataFrame([['M',234,'h'],['F',123,'a'],['M',99,'p'],['F',122,'a'],['F',444,'h']],columns=['gn','score','rate'])

In [87]:
df

gn  score rate
0  M    234    h
1  F    123    a
2  M     99    p
3  F    122    a
4  F    444    h

In [88]:
df_lb=df.copy()
lec=LabelEncoder()
df_lb['gn']=lec.fit_transform(df_lb['gn'])
df_lb['rate']=lec.fit_transform(df_lb['rate'])
df_lb

gn  score  rate
0   1    234     1
1   0    123     0
2   1     99     2
3   0    122     0
4   0    444     1

In [89]:
df_gd=pd.get_dummies(df)
df_gd

score  gn_F  gn_M  rate_a  rate_h  rate_p
0    234     0     1       0       1       0
1    123     1     0       1       0       0
2     99     0     1       0       0       1
3    122     1     0       1       0       0
4    444     1     0       0       1       0

In [90]:
df_oh=df.copy()
ohe=OneHotEncoder()
df_oh=ohe.fit_transform(df_oh).toarray()
df_oh

array([[0., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1., 0.]])

In [92]:
df_oe=df.copy()
ore=OrdinalEncoder()
df_oe=ore.fit_transform(df_oe)
df_oe

array([[1., 3., 1.],
       [0., 2., 0.],
       [1., 0., 2.],
       [0., 1., 0.],
       [0., 4., 1.]])

In [63]:
data =pd.DataFrame(pd.Series(['good','bad','worst','good', 'good', 'bad']))
data

0
0   good
1    bad
2  worst
3   good
4   good
5    bad

In [64]:
dfg = pd.get_dummies(data)
dfg

0_bad  0_good  0_worst
0      0       1        0
1      1       0        0
2      0       0        1
3      0       1        0
4      0       1        0
5      1       0        0

In [93]:
df_lb.dtypes

gn       int64
score    int64
rate     int64
dtype: object

In [100]:
df_gd.dtypes

score     int64
gn_F      uint8
gn_M      uint8
rate_a    uint8
rate_h    uint8
rate_p    uint8
dtype: object