<a href="https://colab.research.google.com/github/praveen310194/data_science/blob/master/Hyper_parameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC
import numpy as np
import pandas as pd

In [ ]:
iris=load_iris()

In [ ]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris['target']
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [ ]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
df['flower'].value_counts()

2    50
1    50
0    50
Name: flower, dtype: int64

In [ ]:
df['flower_names'] = df['flower'].apply(lambda x: iris.target_names[x])

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  ...  flower  flower_names
0                5.1               3.5  ...       0        setosa
1                4.9               3.0  ...       0        setosa
2                4.7               3.2  ...       0        setosa
3                4.6               3.1  ...       0        setosa
4                5.0               3.6  ...       0        setosa

[5 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.25)

In [ ]:
model = SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test, y_test)

0.9210526315789473

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
kernels = ['rbf', 'linear']
cc = [1,10,20]
avg_scores = {}
for k in kernels:
  for c in cc:
    cv_scores=cross_val_score(SVC(kernel=k,C=c,gamma='auto'),iris.data,iris.target,cv=5)
    avg_scores[k + '_' + str(c)] = np.average(cv_scores)

avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [ ]:
from sklearn.model_selection import GridSearchCV
#  GridSearchCV(model, {
#     'C': [1,10,20],
#     'kernel': ['rbf','linear']
# }, cv=5, return_train_score=False)

In [ ]:
clf=GridSearchCV(SVC(gamma='auto'),{
    'C': [1, 10, 20],
    'kernel':('linear', 'rbf')
},cv=5, return_train_score=False)

In [ ]:
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.0010385 , 0.00065203, 0.00045848, 0.00056453, 0.00048122,
        0.00060835]),
 'mean_score_time': array([0.00054083, 0.00037436, 0.00028162, 0.00029697, 0.00027776,
        0.00030723]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.98      , 0.96666667,
        0.96666667]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'}],
 'rank_test_score': array([1, 1, 4, 1, 6, 5], dtype=int32),
 'split0_test_score': array([0.96666667, 0.96

In [ ]:
gcv = pd.DataFrame(clf.cv_results_)
gcv

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001039      0.000825  ...        0.016330                1
1       0.000652      0.000032  ...        0.016330                1
2       0.000458      0.000027  ...        0.038873                4
3       0.000565      0.000022  ...        0.016330                1
4       0.000481      0.000044  ...        0.042164                6
5       0.000608      0.000077  ...        0.036515                5

[6 rows x 15 columns]

In [ ]:
gcv[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.980000
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.966667

In [ ]:
dir(clf)

In [ ]:
clf.best_score_

0.9800000000000001

In [ ]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

**Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. This is useful when you have too many parameters to try and your training time is longer. It helps reduce the cost of computation**

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
rs = RandomizedSearchCV(SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)

In [ ]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='auto', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   iid='deprecated', n_iter=2, n_jobs=None,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [ ]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1       1       linear         0.980000