<a href="https://colab.research.google.com/github/praveen310194/data_science/blob/master/kfold_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [ ]:
df = load_iris()

In [ ]:
dir(df)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [ ]:
df['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
x=df['data']
x.shape

(150, 4)

In [ ]:
df['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
y=df['target']
y.shape

(150,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [ ]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')

In [ ]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr.score(x_test,y_test)

1.0

In [ ]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

1.0

In [ ]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

In [ ]:
ds=DecisionTreeClassifier()
ds.fit(x_train, y_train)
ds.score(x_test, y_test)

1.0

In [ ]:
models=[lr,svm,rf,ds]
def get_score(md,x_train,y_train,x_test,y_test):
  md.fit(x_train,y_train)
  return md.score(x_test,y_test)

In [ ]:
for i in models:
  print(get_score(i,x_train,y_train,x_test,y_test))

1.0
1.0
1.0
1.0


In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [ ]:
x[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
for train_index,test_index in kf.split(x[0:5]):
  print(train_index,test_index)

[1 2 3 4] [0]
[0 2 3 4] [1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


In [ ]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11]):
  print(train_index,test_index)

[ 3  4  5  6  7  8  9 10] [0 1 2]
[ 0  1  2  5  6  7  8  9 10] [3 4]
[ 0  1  2  3  4  7  8  9 10] [5 6]
[ 0  1  2  3  4  5  6  9 10] [7 8]
[0 1 2 3 4 5 6 7 8] [ 9 10]


In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [ ]:
lr_score=[]
ds_score=[]
svm_score=[]
rf_score=[]

for train_index,test_index in folds.split(x,y):
  x_tr,x_ts,y_tr,y_ts=x[train_index],x[test_index],y[train_index],y[test_index]
  lr_score.append(get_score(lr, x_tr,  y_tr, x_ts,y_ts))
  ds_score.append(get_score(ds, x_tr, y_tr, x_ts, y_ts))
  svm_score.append(get_score(svm, x_tr, y_tr, x_ts, y_ts))
  rf_score.append(get_score(rf, x_tr,  y_tr, x_ts,y_ts))


In [ ]:
lr_score

[1.0, 0.9666666666666667, 0.9333333333333333, 0.9, 1.0]

In [ ]:
ds_score

[0.9666666666666667, 0.9666666666666667, 0.9, 0.9666666666666667, 1.0]

In [ ]:
svm_score

[0.9666666666666667, 1.0, 0.9666666666666667, 0.9666666666666667, 1.0]

In [ ]:
rf_score

[0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 0.9333333333333333,
 1.0]

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(lr,x,y,cv=5)

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [ ]:
cross_val_score(ds,x,y,cv=5)

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [ ]:
cross_val_score(svm,x,y,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
cross_val_score(rf,x,y,cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.86666667, 1.        ])